modLoader="javafml" #mandatory
loaderVersion="[31,)"

[[mods]] #mandatory
modId="travmod"
version="1.0"
displayName="Travel Mod"
credits="Thanks to those who supported me"
authors="T_VDP"
description='''
A mod developed as a fun project to work on.
'''
